version: "3.6"
services:
  api:
    user: ${UID}:${GID}
    image: fastapi
    build:
      args:
        - UID=${UID}
        - GID=${GID}
      context: ./api
      target: build
    ports:
      - "80:80"
    depends_on:
      - redis
      - model
    volumes:
      - type: bind
        source: ./api/middleware.py
        target: /home/mlapi/middleware.py
      - type: bind
        source: ./api/app.py
        target: /home/mlapi/app.py

  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"

  model:
    user: ${UID}:${GID}
    image: ml_service
    build:
      args:
        - UID=${UID}
        - GID=${GID}
      context: ./model
      target: build
    depends_on:
      - redis
    volumes:
    - type: bind
      source: ./model/ml_service.py
      target: /src/ml_service.py
    - type: bind
      source: ./model/settings.py
      target: /src/settings.py
